name: linq_samples_in_dart
description: 101 LINQ samples from learn.microsoft implemented in Dart.
version: 1.0.0
homepage: https://github.com/neurot/101-linq-samples-in-dart 

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
